version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=administrador
      - POSTGRES_PASSWORD=administrador
      - POSTGRES_DB=trabajo-final

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: juanrhim@gmail.com
      PGADMIN_DEFAULT_PASSWORD: tiandihuy1
    ports:
      - "80:80"
    depends_on:
      - postgres